### ISSUE TITLE
Expose username and group from the appropriate headers

### ISSUE THREAD

**Issue by braghettos** [kubernetes/apiserver#110]
Hi everyone! We're implementing an aggregation layer leveraging the apiserver package. In our use case we need to retrieve the headers in order to understand who's the user making the request.

We were looking at the documentation: https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/#extension-apiserver-authenticates-the-request - in particular the following paragraph:

Check that the TLS connection was authenticated using a client certificate which:
- Was signed by the CA whose certificate matches the retrieved CA certificate.
- Has a CN in the list of allowed CNs, unless the list is blank, in which case all CNs are allowed.
- Extract the username and group from the appropriate headers

But it seems that the apiserver package is not exposing these headers. Could anyone help me pointing out if there's a way to retrieve these headers after the authn/authz phases?

Thanks for any help!

**Comment by braghettos** [comment]
To date, we put all the custom logic here =>
https://github.com/kubernetes/apiserver/blob/master/pkg/registry/generic/registry/store.go#L170 that is, after the CR has been taken from the store (etcd). The ideal would be to have the object here in this method
https://github.com/kubernetes/apiserver/blob/master/pkg/authentication/user/user.go#L20

**Comment by fedebongio** [comment]
/cc @deads2k @enj @liggitt 

I'll let the experts comment on this one. I have the feeling that there is a reason why such functionality is not already implemented, but I'm not a security expert.

**Comment by enj** [comment]
Use [this code](https://github.com/vmware-tanzu/pinniped/blob/49a57576dd4a9c668ae584d25dbb94e9a115ac63/internal/concierge/server/server.go#L180-L222) as an example for wiring up an aggregated API server correctly.

**Comment by lucasepe** [comment]
Hi @enj thank you very much for your quick response! 

What we would like to do is to access the `user.Info` struct from this `Decorator` => [apiserver/pkg/registry/generic/registry/store.go#L170](https://github.com/kubernetes/apiserver/blob/master/pkg/registry/generic/registry/store.go#L170). 

`Decorator` that is used, for instance, here  => [apiserver/pkg/registry/generic/registry/store.go#L812](https://github.com/kubernetes/apiserver/blob/master/pkg/registry/generic/registry/store.go#L812).

Since this `Decorator` des not expose the `Context`, we can’t do the [`UserFrom(ctx context.Context)`](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/context.go#L75) call.

Taking as reference the [sample-apiserver](https://github.com/kubernetes/sample-apiserver/blob/master/pkg/registry/wardle/fischer/etcd.go#L29), exists a way to access to the `user.Info` who is asking for the resource from within the `Decorator`?

All the best,
Luca

**Comment by enj** [comment]
@lucasepe I am not sure that I would recommend that you change the resource based on the user, but you can do that via:

1. Wrap the `GenericConfig.RESTOptionsGetter` of your server
2. Have it return a `RESTOptions` that further wraps the existing `StorageDecorator`
3. Have the new `StorageDecorator` wrap the `storage.Interface`
4. Have your new `storage.Interface` methods such as `Get` use the request context to perform whatever mutation you want on the returned resource

**Comment by lucasepe** [comment]
Thank you very much @enj ! It works! 

All the best,
Luca
